#!/bin/bash

#time tar -xf EHC_1st.tar.gz
./pigz-2.3.3/pigz -dc /data/EHC_1st.tar.gz | tar xf -  &&  ./preprocess.out &&  R CMD BATCH --no-save --no-restore cal_sales.r  && hadoop fs -mkdir hdfs://master/tmp/Team29 && hadoop fs -copyFromLocal EHC_1st_round.log hdfs://master/tmp/Team29/EHC_1st_round.log

