#!/bin/bash

#time tar -xf EHC_1st.tar.gz
time ./pigz-2.3.3/pigz -dc ./EHC_1st.tar.gz | tar xf -
time python preprocess.py && R CMD BATCH --no-save --no-restore cal_sales.r
time hadoop fs -put EHC_1st_round.log .

